#!/usr/bin/env node
// Regenerates src/icons/allIcons.ts from src/icons/svg/*.svg.
//
//   node scripts/generate-icons.mjs          # rewrite the barrel
//   node scripts/generate-icons.mjs --check  # exit 1 if the barrel is stale
//
// Each SVG becomes a named string constant (`bondSvg`, `newOrderSvg`, …) plus
// an entry in the `icons` record keyed by its kebab-case file name. The
// helper functions at the bottom are emitted verbatim so the module stays a
// single self-contained file (origin: stern-bak icons-svg/allIcons.ts).
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const svgDir = resolve(pkgRoot, 'src/icons/svg');
const outFile = resolve(pkgRoot, 'src/icons/allIcons.ts');
const check = process.argv.includes('--check');

const toConst = (key) => key.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()) + 'Svg';
const escapeTemplate = (s) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const files = readdirSync(svgDir)
  .filter((f) => f.endsWith('.svg'))
  .sort((a, b) => a.localeCompare(b, 'en'));

if (files.length === 0) {
  console.error(`[generate-icons] no SVG files found in ${svgDir}`);
  process.exit(1);
}

const entries = files.map((file) => {
  const key = basename(file, '.svg');
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(key)) {
    console.error(`[generate-icons] icon file names must be kebab-case: ${file}`);
    process.exit(1);
  }
  const svg = readFileSync(resolve(svgDir, file), 'utf8').trim();
  return { key, name: toConst(key), svg };
});

const header = `/**
 * AUTO-GENERATED by scripts/generate-icons.mjs from src/icons/svg/*.svg.
 * Do not edit by hand — run \`npm run generate:icons\` instead.
 *
 * Every icon is exported as a string constant (\`<camelName>Svg\`) and via the
 * \`icons\` record keyed by its kebab-case file name. Most icons use
 * \`currentColor\` so they inherit CSS colour; the curated fixed-palette set
 * (see allIcons.test.ts) carries literal fills by design.
 *
 * Origin: stern-bak packages/design-system/icons-svg/allIcons.ts.
 */

`;

const constants = entries
  .map(({ name, svg }) => `export const ${name} = \`${escapeTemplate(svg)}\`;`)
  .join('\n\n');

const record = [
  '/** Every icon keyed by its kebab-case name. */',
  'export const icons = {',
  ...entries.map(({ key, name }) => `  '${key}': ${name},`),
  '} as const;',
  '',
  'export type IconKey = keyof typeof icons;',
  '',
  '/** Total number of bundled icons. */',
  `export const ICON_COUNT = ${entries.length};`,
].join('\n');

const footer = `
/** Compatibility alias — string-keyed view of \`icons\` used by DynamicIcon and data-URL helpers. */
export const MARKET_ICON_SVGS: Record<string, string> = icons;

/**
 * Convert any SVG string to a data URL with a specific color.
 * Replaces "currentColor" with the provided colour string.
 * Strips HTML comments and normalizes whitespace for clean base64 encoding.
 *
 * This is the SINGLE implementation — all icon-to-data-URL conversion
 * should go through this function.
 */
export function svgToDataUrl(svg: string, color: string = '#ffffff'): string {
  if (!svg) return '';
  const clean = svg
    .replace(/currentColor/g, color)
    .replace(/<!--[\\s\\S]*?-->/g, '') // strip HTML comments
    .replace(/\\s+/g, ' ') // collapse whitespace
    .trim();
  return \`data:image/svg+xml;base64,\${btoa(unescape(encodeURIComponent(clean)))}\`;
}

/**
 * Convert a bundled icon (by key name) to a data URL with a specific colour.
 * Looks up the SVG string from \`icons\` and delegates to svgToDataUrl.
 */
export function marketIconToDataUrl(iconKey: string, color: string = '#ffffff'): string {
  const svg = MARKET_ICON_SVGS[iconKey];
  if (!svg) return '';
  return svgToDataUrl(svg, color);
}

// ─── System button convenience exports ─────────────────────────────────
/** Wrench icon — Tools dropdown button. */
export const TOOLS_SVG = icons['wrench'];
/** Gear icon — settings / editor menu item. */
export const SETTINGS_SVG = icons['settings'];
/** Refresh icon — "Reload" menu item. */
export const REFRESH_SVG = icons['refresh'];
/** Code/terminal icon — "Developer Tools" menu item. */
export const CODE_SVG = icons['code'];
/** Download icon — "Export Config" menu item. */
export const DOWNLOAD_SVG = icons['download'];
/** Upload icon — "Import Config" menu item. */
export const UPLOAD_SVG = icons['upload'];
/** Sun icon — theme toggle icon shown in dark mode. */
export const SUN_SVG = icons['sun'];
/** Moon icon — theme toggle icon shown in light mode. */
export const MOON_SVG = icons['moon'];
/** Eye icon — "Show/Hide" menu item. */
export const EYE_SVG = icons['eye'];
`;

const output = `${header}${constants}\n\n${record}\n${footer}`;

for (const required of [
  'wrench',
  'settings',
  'refresh',
  'code',
  'download',
  'upload',
  'sun',
  'moon',
  'eye',
]) {
  if (!entries.some((e) => e.key === required)) {
    console.error(`[generate-icons] missing required system icon: ${required}.svg`);
    process.exit(1);
  }
}

if (check) {
  const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
  if (current !== output) {
    console.error('[generate-icons] src/icons/allIcons.ts is stale — run `npm run generate:icons`.');
    process.exit(1);
  }
  console.log('[generate-icons] up to date.');
} else {
  writeFileSync(outFile, output);
  console.log(`[generate-icons] wrote ${entries.length} icons to ${outFile}`);
}
