import { z } from 'zod';
import { withEditor } from '../meta.js';

/**
 * Cell data types, matching AG Grid's `cellDataType` plus the array types
 * AdapTable adds for sparklines and badges.
 */
export const CellDataType = z.enum([
  'text',
  'number',
  'boolean',
  'date',
  'dateString',
  'object',
  'textArray',
  'numberArray',
  'tupleArray',
  'objectArray',
]);
export type CellDataType = z.infer<typeof CellDataType>;

export const SCALAR_DATA_TYPES = ['text', 'number', 'boolean', 'date', 'dateString'] as const;
export const ARRAY_DATA_TYPES = ['textArray', 'numberArray', 'tupleArray', 'objectArray'] as const;

/** Reference to a grid column by its AG Grid colId. */
export const ColumnId = withEditor(z.string().min(1), { 'x-editor': 'column', title: 'Column' });
export type ColumnId = z.infer<typeof ColumnId>;

/** Ordered list of column ids. */
export const ColumnIds = withEditor(z.array(z.string().min(1)), { 'x-editor': 'columns', title: 'Columns' });
export type ColumnIds = z.infer<typeof ColumnIds>;

/**
 * Built-in column types usable in `Scope.columnTypes`. Custom AG Grid `type`
 * strings are also allowed; these are the ones the engine generates.
 */
export const BUILT_IN_COLUMN_TYPES = [
  'calculatedColumn',
  'freeTextColumn',
  'actionColumn',
  'hiddenColumn',
  'pivotGrandTotal',
  'pivotColumnTotal',
  'pivotAggregationTotal',
  'pivotAnyTotal',
] as const;

/** Reserved column ids generated by AG Grid or the engine. */
export const RESERVED_COLUMN_IDS = {
  autoGroup: 'ag-Grid-AutoColumn',
  autoGroupPrefix: 'ag-Grid-AutoColumn-',
  selection: 'ag-Grid-SelectionColumn',
  tree: '_ag-Grid-AutoColumn_',
  pivotPrefix: 'pivot_',
} as const;

/**
 * Column information the engine derives from the live grid and hands to editors
 * and the assistant. Not persisted in the config document.
 */
export const ColumnInfo = z.object({
  id: z.string(),
  field: z.string().optional(),
  header: z.string(),
  dataType: CellDataType,
  columnTypes: z.array(z.string()).default([]),
  sampleValues: z.array(z.unknown()).default([]),
  distinctCount: z.number().int().optional(),
  editable: z.boolean().default(false),
  isPrimaryKey: z.boolean().default(false),
  isSpecial: z.boolean().default(false).describe('Calculated, free-text or action column'),
});
export type ColumnInfo = z.infer<typeof ColumnInfo>;
